import Foundation

/// User-facing settings backed by JSON in Application Support.
///
/// On every mutation we (a) persist to `settings.json` and (b) generate a
/// `runtime.conf` in Ghostty's syntax which `GhosttyRuntime.reloadConfig()`
/// re-loads to apply changes to every live surface.
struct AppSettings: Codable, Equatable {
    var fontFamily: String = ""             // empty = libghostty's default
    var fontSize: Double = 13
    var cursorStyle: CursorStyle = .bar
    var theme: String = "TokyoNight Storm"  // default; user can change in Settings or set to "" for none
    var backgroundOpacity: Double = 1.0     // 0.2 … 1.0
    var blurLevel: BlurLevel = .off

    enum CursorStyle: String, Codable, CaseIterable {
        case bar, block, underline
    }

    enum BlurLevel: String, Codable, CaseIterable {
        case off, light, medium, strong
    }

    /// Tolerant decoder so we can rename fields without nuking the user's
    /// saved JSON. Old `windowBlur: Bool` / `blurIntensity: Double` are
    /// silently ignored if they survive in an old settings.json.
    init() {}
    init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        fontFamily = try container.decodeIfPresent(String.self, forKey: .fontFamily) ?? ""
        fontSize = try container.decodeIfPresent(Double.self, forKey: .fontSize) ?? 13
        cursorStyle = try container.decodeIfPresent(CursorStyle.self, forKey: .cursorStyle) ?? .bar
        theme = try container.decodeIfPresent(String.self, forKey: .theme) ?? "TokyoNight Storm"
        backgroundOpacity = try container.decodeIfPresent(Double.self, forKey: .backgroundOpacity) ?? 1.0
        blurLevel = try container.decodeIfPresent(BlurLevel.self, forKey: .blurLevel) ?? .off
    }

    /// Render as a Ghostty config-file fragment.
    func renderConfigFile() -> String {
        var lines: [String] = ["# Auto-generated by Terminal.app — do not edit."]
        if !fontFamily.isEmpty { lines.append("font-family = \(fontFamily)") }
        lines.append("font-size = \(Int(fontSize))")
        lines.append("cursor-style = \(cursorStyle.rawValue)")
        if !theme.isEmpty { lines.append("theme = \(theme)") }
        lines.append("background-opacity = \(String(format: "%.2f", backgroundOpacity))")
        if blurLevel != .off { lines.append("background-blur = true") }
        return lines.joined(separator: "\n") + "\n"
    }
}
